CREATE TABLE IF NOT EXISTS `ORDER` (
  `ORDER_ID` INT NOT NULL AUTO_INCREMENT,
  `ORDER_DATE` TIMESTAMP NOT NULL,
  `ORDER_COST` FLOAT NOT NULL,
  PRIMARY KEY (`ORDER_ID`)
  );

CREATE TABLE IF NOT EXISTS `PRODUCT` (
  `PRODUCT_ID` INT NOT NULL AUTO_INCREMENT,
  `PRODUCT_NAME` VARCHAR(100) NOT NULL,
  `PRODUCT_COST` FLOAT NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`)
  );

CREATE TABLE IF NOT EXISTS `ORDER_PRODUCT` (
  `ORDER_ID` INT NOT NULL,
  `PRODUCT_ID` INT NOT NULL,
  PRIMARY KEY (`ORDER_ID`, `PRODUCT_ID`),
  CONSTRAINT `ORDER_SUB_ID_FK` 
     FOREIGN KEY (`ORDER_ID`) 
     REFERENCES `ORDER` (`ORDER_ID`),
  CONSTRAINT `PRODUCT_SUB_ID_FK` 
     FOREIGN KEY (`PRODUCT_ID`) 
     REFERENCES `PRODUCT` (`PRODUCT_ID`)
);
