spring:
  datasource:
    url: jdbc:mysql://localhost/spring-lombok-migration
    username: root
    password: hjIt64-JkeUY
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
  flyway:
    enabled: true
    validate-on-migrate: true
